### PR TITLE
repair-ship-when-dock: Repair the ship at the station before undocking.

### PR DESCRIPTION
**Pull request by focabr**
An example BOT implementation for Eve Online Mining that uses repairshopwindows, you can repair all items on the dock before undocking it if you set 'repair-ship-when-dock=yes'.

If you have any question, feel free to contact me.

Best regards

### CODE REVIEW

**Comment by focabr** [comment]
Sorry for the delay, I sent the session recording.

session-recording-2023-02-28T03-22-56.zip

**Comment by Viir** [comment]
Hello Marcos, thank you for sharing your bot with us!
Since you have published it, anybody can now benefit from your contribution.

The contents of your pull request seek to change a particular repository of example programs others use as a learning resource. Because many others follow these examples, the criteria for changing them are stricter than other channels.

> Sorry for the delay, I sent the session recording.

No worries, I am slow to respond this week anyway. Too much other stuff going on this week.

> session-recording-2023-02-28T03-22-56.zip

As far as I understand this recording, it repaired a drone in that session.
Would it be worse to shorten the setting name to `repair-when-dock`?

I am wondering why the setting is named `repair-ship-when-dock`
To mee it seems to contradict this part of the description you added: 'before undocking'
Why not name it `repair-before-undocking`? That would be closer to your description.

**Comment by focabr** [comment]
> The contents of your pull request seek to change a particular repository of example programs others use as a learning resource. Because many others follow these examples, the criteria for changing them are stricter than other channels.
I expect nothing less from your review. I'm always doing my best. If you have any comments, feel free to contact me.


> As far as I understand this recording, it repaired a drone in that session. Would it be worse to shorten the setting name to `repair-when-dock`?
> 
> I am wondering why the setting is named `repair-ship-when-dock` To mee it seems to contradict this part of the description you added: 'before undocking' Why not name it `repair-before-undocking`? That would be closer to your description.

Perfect, it looks really good! I'm going to rename it to `repair-before-undocking`.

Sorry, I have no justification for my mistake, but I think I may have gotten confused during the translation because I did it in parts. lol

**Comment by focabr** [comment]
Viir,

I've made the adjustments, If you have any more question, please let me know.

Best regards

**Comment by Viir** [comment]
Thank you for the fast update!

LGTM

In alignment with our contributor reward program, I will add one million credits to your BotLab account at https://reactor.botlab.org/billing
💸
With these credits, you can run five hundred hours of online sessions.

**Pull request merged**
