### PR TITLE
Implementation Mining in fleet with an orca or a rorqual 

### PR DESCRIPTION
**Pull request by focabr**
How are you doing? I hope you're okay. 

I apologize for the English and also the code, and the first comes that I program in Elm.

I tried to create in the most clean way possible without changing too much your code.

I did a simple implementation so that if he finds the fleet hangar inside the inventory he moves the ore when it is greater than 65%, if he is more and does not see the miners he will click on the fleet hangar, if he does not find the fleet hangar he goes to a station.

I am available for any doubt or questioning. In case you are not satisfied how the code was written can tell me so I can improve.

### CODE REVIEW

**Comment by Viir** [comment]
Hello Marcos, thank you for sharing your bot with us.

I have looked at the code, and there is one thing that I do not yet understand:
The code looks like you compare the value of the setting `unload-fleet-hangar-percent` with a reading from the mining hold. Based on the name of this setting, I had expected the bot to compare it to a reading from the fleet hangar.
What do you think about this comparison in particular?
https://github.com/focabr/bots/blob/2a6d4b977480b91fa99f13ad15ea23f755bef2c5/implement/applications/eve-online/eve-online-mining-bot/Bot.elm#L493-L515

**Comment by focabr** [comment]
yes, you are correct! I will send a new PR ASAP.

To clarify, the bot is to be used by all mining bargers like the hulk, retrive, Venture...

To use the bot, you must be in a fleet with an orca or a rorqual, so that the ship can gain access to a fleet hangar.

Sent Img Hulk ship

image

**Comment by Viir** [comment]
Thank you for the clarification!

Now that looks different. That bot will be very useful for many people!

In alignment with our contributor reward program, I will add one million credits to your BotLab account at https://reactor.botlab.org/billing
With these credits, you can run five hundred hours of online sessions.

**Comment by focabr** [comment]
Viir,

Thank you very much for the reward.

Several tests were performed, one of them the bot ran for almost 3 hours using the parameter defined with the value unload-fleet-hangar-percent=51 and everything went as planned, then I ran the bot for another 2 hours without setting this parameter leaving the default value, everything went normally.

Any questions or problems do not hesitate to contact me.

**Comment by Viir** [comment]
Thank you for the update!
Since testing revealed no issues, I am merging this now into the examples repository.
As the bot also covers scenarios without a fleet hangar, I have no objections to using it as the main example for mining.

The addition of the one million credits should be visible on your account balance by now.

**Pull request merged**
