### PR TITLE
This will make the bot dock when its out of drones

### PR DESCRIPTION
**Pull request by focabr**
Hi,

This weekend, I lost my hulk ship, analyzing the session logs I understood what happened, it was very interesting, kkkkk

Here are the results of some fights:

1st. - hulk vs rat: 1 lost drone
2nd. - hulk vs rat: 2 lost drone
3rd. - hulk vs rat: 2 lost drone
4th. - hulk vs rat: hulk warp in the asteroid belt without any drone, was attacked by the rats and when the hull was below 70% he could not dock at the station (by the images you can imagine what happened) it must have been caught on the web.

That's why I developed this PR in order to prevent this from happening again, but I couldn't resolve one issue, after the drones run out and the bot sends the ship back to the station, but later the ship is leaving and entering the station.

As a workaround this is acceptable, but no ideas on how to solve this problem without having to change too much in the code. I'm open to suggestions. :D

For the future in this case there could be some paths, for example:

- When docking at the station, check the amount of drones and if you need to take more in the hangar;
- Have setting to log out of the game after docking in the station;

Unfortunately today I still don't have enough knowledge in the Elm language to develop this.

### CODE REVIEW

**Comment by Viir** [comment]
Thank you for sharing your observation!

Also, thank you for creating the new bot program code. Did you test it already?
Running a test takes less than five minutes because you don't have to start a game client for testing.
You can use the recording of your session that you inspected instead of a game client.
Use the `--environment` option to input your session recording as the replacement of the game client:
```
botlab  play  --environment="C:\Downloads\session-recording-2023-01-19T13-01-01.zip"  C:\your-bot-program-directory
```

The BotLab client then shows you here it has successfully loaded the test environment:

image

(If you send me the session recording, I could run that test here.)

**Comment by focabr** [comment]
Hello, how are you, hope everyone is well out there.

Yes, I did several tests for a few hours with and without the new configuration and it worked fine.

Thank you very much for the recommendation on how to use the test environment, I will always use it.

I ran the tests again and then used it in the test environment, it worked correctly. I will send you the session records of both by email. I will now use this as a good practice when submitting a new PR.

> I have looked at the program code briefly, and it seems like there is a condition missing.
Feel free to say what you missed about the program code.

**Comment by Viir** [comment]
Looking at it again now, I understand it better: I confused the two sides of the branch on whether the Drones window is visible. Now it makes sense. I was surprised to see no check for the number of drones if the window was visible. But maybe the game client hides the Drones window when there are no drones. Then we don't need such a check.

**Comment by focabr** [comment]
Viih,

Was there any doubt about the code or do you have any suggestion to be implemented in the code?

Feel free to suggest or say anything.

**Comment by focabr** [comment]
> Looking at it again now, I understand it better: I confused the two sides of the branch on whether the Drones window is visible. Now it makes sense. I was surprised to see no check for the number of drones if the window was visible. But maybe the game client hides the Drones window when there are no drones. Then we don't need such a check.
> 
> Lesson learned: Reading the test results was easier than understanding the program code.


Viih,

I see no problem in implementing the drone check, but the game client itself hides the drone window when there are no drones.

**Comment by Viir** [comment]
> Was there any doubt about the code or do you have any suggestion to be implemented in the code?

Yes, I wrote the above questions because I had doubts about the bot behavior resulting from the new program code. But that was only because I failed to understand the program code and did not have a model of the game client. That doubt was resolved when I got the test results 👍

> the game client itself hides the drone window when there are no drones.

Thank you for sharing this observation. I was not aware of this behavior of the game client when reading the program code earlier.

**Comment by Viir** [comment]
Since we have tested the docking, let's see how we can solve the challenge of (avoiding) undocking:

> As a workaround this is acceptable, but no ideas on how to solve this problem without having to change too much in the code. I'm open to suggestions. :D

I see a simple solution:

+ Add a field `dronesWindowWasVisibleInSpace : Maybe Bool` to the bot memory.
+ Update that field in `updateMemoryForNewReadingFromGame`: Set it to `Just False` or `Just True` when we are in space.
+ Expand the function responsible for undocking to branch on this new field in the bot memory (if the new setting is also enabled).
+ Bonus point for readability of the program code, increasing symmetry between the functions for docking and undocking: Change the new branch in `returnDronesAndRunAwayIfHitpointsAreTooLowOrWithoutDrones` to reuse the new field in the bot memory.

I have implemented that here: https://github.com/Viir/bots/commit/5dffb16ccc5f576580029a288245b6058701d45e

Does that work for you to fix the undocking?

I noticed a bug in the bot program code that will sometimes break the simulation. In that case, it continues waiting for the completion of a specific task. I will need to change this (maybe to wait only on a class of tasks). In the meantime, I am afraid the simulation does not always produce predictive results (The status text will continue showing the results from an earlier step in that case)

**Comment by focabr** [comment]
Thank you for your hard work and timely response.

Yes, a simple and efficient solution.

I just had a doubt in the code below, it is referring to the shipUI shouldn't it be the dronesWindow?

```elm
        dronesWindowWasVisibleInSpace =
            if **context.readingFromGameClient.shipUI** == Nothing then
                botMemoryBefore.dronesWindowWasVisibleInSpace

            else
                Just (context.readingFromGameClient.dronesWindow /= Nothing)


```

**Comment by Viir** [comment]
> I just had a doubt in the code below, it is referring to the shipUI shouldn't it be the dronesWindow?
> 
> if context.readingFromGameClient.shipUI == Nothing then

If you would replace it with dronesWindow, in which case would you get `Just False` out of the enclosing expression?

**Comment by Viir** [comment]
By the way: I see that expression you mentioned is so simple that we can easily copy it into Elm Explorer:

image

**Comment by focabr** [comment]
Hey,
Thanks for the explanations. What is the idea behind when you use shipUI instead of dronesWindow?

I created some test scenarios and would like to share them here with you.

**Scenario 1**

**Situation:** Ship in the asteroid belt with drones and mining with dock-when-without-drones=yes.

**Simulation:** Ship without drones.

**Result:** Bot successfully detected which ship was without the drones and sent the ship to the station and there it stayed.  SUCCESS!

**Scenario  2**

Situation: Ship still at the station.

Simulation: I made the ship undock from the station manually.

Result: the bot detected that she was still in the drones and ordered her to dock again.
SUCCESS!

**Scenario  3**

**Comment by Viir** [comment]
> Thanks for the explanations. What is the idea behind when you use shipUI instead of dronesWindow?

As far as I see, this is not the case. Instead, the code I linked uses both. I highlighted it in this screenshot:

image

If you were referring to the upper of the two marked parts: I think if we would replace the upper usage of `shipUI`, then we would not anymore get the `Just False` value in `dronesWindowWasVisibleInSpace`.

Using the `shipUI` here might not be sufficient. Ultimately, we need a recording from a game client to test if that works.
For example: When we test with a recording, we might find it works better when we combine `shipUI` and `overviewWindow`.

Or maybe, using only`overviewWindow` there would be enough.

So the upper expression for the branch was just the first idea of what might work. When we see that it does not work, we change it.

> When the Mining Hold was full, the bot sent it to dock at the station, docking there it got stuck saying it had no drones. FAILURE.

I am going to speculate here to illustrate the thinking process:
I am wondering: Why did it fail here?
It could be that the drone window disappeared earlier than the ship UI in your game client.
Remember this observation you made earlier:

> but the game client itself hides the drone window when there are no drones.

The bot program I linked above interprets it this way: When the drone window is not visible, we have no drones (Yes, that means a failure if we manually minimize the drone window)

Using the recording you sent me, we can check if the theory described above is true.

**Comment by Viir** [comment]
Thank you for the thorough testing 👍 

> I recorded a session with these scenarios and sent it by email.
> 
> session-recording-2023-01-26T00-37-54.zip

Awesome, here we can see why it failed. When you select event 1418 in that session, you see the scenario I speculated above. You can see it in the reading from the game client. But even just the status text from the bot allows us to infer the same.
In event 1418, the bot status text also contains this portion:
```
Shield HP at 100%. Found 2 mining modules. I do not see the drones window.
```
From this output, we can infer that the ship UI was visible, and the drone window was not visible. (In the program code, we find it reads the hitpoints from the ship UI)

To fix this issue, I will adapt the program code to `session-recording-2023-01-26T00-37-54`.

**Comment by Viir** [comment]
I adapted the program code to `session-recording-2023-01-26T00-37-54`.

You can see the commit at <https://github.com/Viir/bots/commit/73c2b58ed7940f6fba4b92b88c1ba7016cbc2532>

The previous example program code was based on the assumption that the drone window would be visible at least as long as the ship UI.
In session-recording-2023-01-26T00-37-54, we see that assumption was wrong: The drone window disappeared two steps earlier than the ship UI.

This commit replaces the earlier assumption with the following assumption: When we dock, the ship UI disappears at most four readings/steps later than the drone window.
The number four is coded in the declaration `dockWhenDroneWindowInvisibleCount` and can be adjusted there if needed.

The effect of the change in the program code can be seen in event `1426` of `session-recording-2023-01-26T00-37-54`: In that event, the previous program code decided to stay docked, and the new program decided to undock.

image

**Comment by Viir** [comment]
As far as my observations go, the variant in commit 73c2b58ed7940f6fba4b92b88c1ba7016cbc2532 solved this problem you mentioned earlier:

> but I couldn't resolve one issue, after the drones run out and the bot sends the ship back to the station, but later the ship is leaving and entering the station.

I am not aware of a reason not to merge this version.
If you don't see any issues, I will merge it soon.

**Comment by focabr** [comment]
Viir,

I did a new test undocking from the station with the 5 drones, as soon as the ship left the station the bot detected that it was not seeing the drones screen and docked again at the station, and it was undocking and docking for a while.

I emailed you the new session-recording-2023-01-28T16-23-02.zip

**Comment by Viir** [comment]
Thank you for testing. Now I see I made a mistake in commit 73c2b58ed7940f6fba4b92b88c1ba7016cbc2532:
The logic is inverted, this should be `False` instead of `True`:

image

Since I only tested with event 1426, I did not notice that problem.
But, in event 71 of `session-recording-2023-01-26T00-37-54`, we can see the bug causing a wrong decision to dock:

image

**Comment by focabr** [comment]
Viir,


Fantastic, it worked perfectly!

I tested it with 5 drones in the drone bay, with 4, with 3, with 2, with 1 these cases it worked normally. When he was out of drones he undocked and docked again.

In case the ship was mining on the miner's asteroid and ran out of drones, the BOT ordered it to dock and never left.

Everything perfect. Thank you.

**Comment by Viir** [comment]
Awesome, thank you :+1:
I now merged the new drones feature in the main branch here.

**Pull request closed without merging**
